Updated hack-* scripts.

diff --git a/hack-off b/hack-off
--- a/hack-off
+++ b/hack-off
@@ -1,21 +1,30 @@
 #!/usr/bin/env bash
 set -eu
 
-DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
-
-. "$DIR/common-setup.sh"
+DIR="$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)"
+source "$DIR/common-setup.sh"
 
 REPO="$1"
+DIFF=
+DIFF_ERR=
+STATUS=
+STATUS_ERR=
 
-if [ ! -d "$REPO" ] ; then
-    echo "Error: no such directory: $REPO"
-    exit 1
-fi
+checkRepo() {
+    if [[ ! -d "$REPO" ]] ; then
+        echo "Error: no such directory: $REPO"
+        exit 1
+    fi
+}
+checkRepo
 
-DIFF="$(git -C "$REPO" diff HEAD)"
-DIFF_ERR=$?
-STATUS="$(git -C "$REPO" status --porcelain --ignored)"
-STATUS_ERR=$?
+getStatus() {
+    DIFF="$(git -C "$REPO" diff HEAD)"
+    DIFF_ERR=$?
+    STATUS="$(git -C "$REPO" status --porcelain --ignored)"
+    STATUS_ERR=$?
+}
+getStatus
 
 if [ "$DIFF_ERR" -ne 0 -o "$STATUS_ERR" -ne 0 ] ; then
     >&2 echo "Error: could not determine whether $REPO contains unsaved modifications"
@@ -50,3 +59,10 @@ rm -rf "$REPO"
 mkdir "$REPO"
 git_thunk >"$REPO/default.nix"
 echo "$GIT_MANIFEST" >"$REPO/git.nix"
+
+# main() {
+#     checkRepo
+#     getStatus
+# }
+
+# main "$@"
