Rewrite with haskell.nix (experimental)

diff --git a/scripts/work-on b/scripts/work-on
--- a/scripts/work-on
+++ b/scripts/work-on
@@ -1,6 +1,9 @@
 #!/usr/bin/env bash
 set -euo pipefail
 
+echo "WARN: Work-on is not supported/deprecated in this release of reflex-platform, expect failures!"
+exit 1
+
 DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )
 
 if [ "$#" -lt 2 ] ; then
@@ -32,4 +35,4 @@ fi
 PACKAGE_INVOCATION="$(package_invocation "$EFFECTIVE_PLATFORM" "$PACKAGE")"
 
 terminate_logging
-nix-shell $NIXOPTS -E "let this = import $DIR/. {}; in this.workOn $EFFECTIVE_PLATFORM $PACKAGE_INVOCATION" "$@"
+#nix-shell $NIXOPTS -E "let this = import $DIR/. {}; in this.workOn $EFFECTIVE_PLATFORM $PACKAGE_INVOCATION" "$@"
